# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb and the android orb
  welcome: circleci/welcome-orb@0.4.1
  android: circleci/android@0.2.1
# Declare jobs
jobs:
  build-android:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew assembleDebug
    environment:
      # kotlin.incremental=false and kotlin.compiler.execution.strategy=in-process are required due to an issue with the Kotlin compiler in memory constrained environments: https://youtrack.jetbrains.com/issue/KT-15562
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  build-android:
    jobs:
      - build-android